export const CartActionTypes = {
  TOGGLE_VISIBILITY: "TOGGLE_VISIBILITY",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  CLEAR_CART_ITEM: "CLEAR_CART_ITEM",
  EMPTY_CART: "EMPTY_CART"
};
